sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t amirinbar/todo-app-docker-vue -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amirinbar/todo-app-docker-vue npm run test

after_success:
  - docker build -t amirinbar/multi-client ./client
  - docker build -t amirinbar/multi-nginx ./nginx
  - docker build -t amirinbar/multi-server ./server
  - docker build -t amirinbar/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push amirinbar/multi-client
  - docker push amirinbar/multi-nginx
  - docker push amirinbar/multi-server
  - docker push amirinbar/multi-worker
  -

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-258435333577'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY